name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v1
      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pub-cache
      - name: Get Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Enable MacOS Desktop
        run: flutter config --enable-macos-desktop
      - name: Get Libs
        run: flutter pub get
        
      - name: Build MacOS Release
        run: flutter build macos --release
      - name: Upload MacOS Release Files
        uses: actions/upload-artifact@v2
        with:
          name: MacOS-Build
          path: build/macos/Build/Products/Release/setup4bmatotp.app/
  
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v1
      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pub-cache
      - name: Get Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Get Libs
        run: flutter pub get
        
      - name: Build Windows Release
        run: flutter build windows --release
      - name: Upload Windows Release Files 
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Build
          path: build/windows/runner/release/
  
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v1
      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pub-cache
      - name: Get Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Dev Depenencies 
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Get Libs
        run: flutter pub get
    
      - name: Build Linux Release
        run: flutter build linux --release
      - name: Upload Linux Release Files
        uses: actions/upload-artifact@v2
        with:
          name: Linux-Build
          path: build/linux/x64/release/bundle/
  
